name: mkdocs

on:
  push:
    branches:
      - master

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install --no-cache-dir -r requirements.txt
      - run: mkdocs gh-deploy
